const riskMatrix = {
    // Weights for the overall risk score calculation
    weights: {
        global: {
            aceptacion: 0.30,
            monitoreo: 0.70
        },
        aceptacion: {
            cliente: 0.60,
            jurisdiccion: 0.20,
            producto: 0.10,
            canal: 0.10
        }
    },

    // Value mappings for each factor
    values: {
        producto: {
            'credito_simple': 1,
            'revolvente': 2, 
            'hipotecario': 1,
            'default': 1
        },
        canal: {
            'sucursales directas': 1.5,
            'agentes': 2,
            'atms': 1,
            'portal internet': 1,
            'cobradores': 3,
            'default': 1.5
        },
        
        jurisdiccion_pais: {
            'Nueva Zelanda': 1,
            'Dinamarca': 1,
            'Finlandia': 1,
            'Suecia': 1,
            'Suiza': 1,
            'Noruega': 1,
            'Singapur': 1,
            'Países Bajos': 1,
            'Canadá': 1,
            'Alemania': 1,
            'Luxemburgo': 1,
            'Reino Unido': 1,
            'Australia': 1,
            'Islandia': 1,
            'Hong Kong': 1,
            'Bélgica': 1,
            'Austria': 1,
            'Estados Unidos de Norteamérica': 1,
            'Irlanda': 1,
            'Japón': 1,
            'Uruguay': 1,
            'Estonia': 1,
            'Francia': 1,
            'Bahamas': 1,
            'Chile': 1,
            'Emiratos Árabes Unidos': 1,
            'Bután': 1,
            'Israel': 1,
            'Polonia': 1,
            'Portugal': 1,
            'Barbados': 1,
            'Taiwán': 1,
            'Catar': 1,
            'Eslovenia': 1,
            'Santa Lucía': 1,
            'San Vicente y las Granadinas': 1,
            'Botsuana': 1,
            'Dominica': 1,
            'Cabo Verde': 1,
            'Lituania': 1,
            'Costa Rica': 1,
            'Brunei': 1,
            'España': 1,
            'Georgia': 1,
            'Letonia': 1,
            'Granada':	1,
            'Chipre':	1,
            'República Checa':	1,
            'Malta':	1,
            'Mauricio':	1,
            'Ruanda':	1,
            'Corea del Sur':	1,
            'Namibia':	1,
            'Eslovaquia':	1,
            'Malasia':	1,
            'Croacia':	1,
            'Jordania':	1,
            'Hungría':	1,
            'Rumania':	1,
            'Cuba':	1,
            'Italia':	2,
            'Arabia Saudita':	2,
            'Santo Tomé y Príncipe':	2,
            'Suriname':	2,
            'Montenegro':	2,
            'Omán':	2,
            'Senegal':	2,
            'Sudáfrica':	2,
            'Grecia':	2,
            'Bahrein':	2,
            'Ghana':	2,
            'Islas Solomón':	2,
            'Serbia':	2,
            'Burkina Faso':	2,
            'Turquía':	2,
            'Kuwait':	2,
            'Túnez':	2,
            'Bulgaria':	2,
            'Brasil':	2,
            'China':	2,
            'India':	2,
            'Bielorrusia':	2,
            'Jamaica':	2,
            'Albania':	2,
            'Bosnia y Herzegovina':	2,
            'Lesoto':	2,
            'Panamá':	2,
            'Mongolia':	2,
            'Zambia':	2,
            'Colombia':	2,
            'Indonesia':	2,
            'República de Macedonia':	2,
            'Marruecos':	2,
            'Liberia':	2,
            'Argentina':	2,
            'El Salvador':	2,
            'Maldivas':	2,
            'Sri Lanka':	2,
            'Kosovo':	2,
            'Benin':	2,
            'Perú':	2,
            'Trinidad y Tobago':	2,
            'Filipinas':	2,
            'Tailandia':	2,
            'Timor Oriental':	2,
            'Gabón':	2,
            'Nigeria':	2,
            'Guayana':	2,
            'Argelia':	2,
            'Egipto':	2,
            'Costa de Marfil':	2,
            'Etiopía':	2,
            'Bolivia':	2,
            'Vietnam':	2,
            'Armenia':	2,
            'Pakistán':	2,
            'Malí':	2,
            'Tanzania':	2,
            'Togo':	2,
            'República Dominicana':	2,
            'Ecuador':	2,
            'Malawi':	3,
            'Honduras':	3,
            'México':	3,
            'Paraguay':	3,
            'Laos':	3,
            'Azerbaiyán':	3,
            'Moldavia':	3,
            'Djibouti':	3,
            'Sierra Leona':	3,
            'Nepal':	3,
            'Kazajstán':	3,
            'Rusia':	3,
            'Ucrania':	3,
            'Irán':	3,
            'Guatemala':	3,
            'Birmania':	3,
            'Papúa Nueva Guinea':	3,
            'Kirguistán':	3,
            'Líbano':	3,
            'Nigeria':	3,
            'Guinea':	3,
            'Mauritania':	3,
            'Mozambique':	3,
            'Nicaragua':	3,
            'Bangladés':	3,
            'Camerún':	3,
            'Gambia':	3,
            'Kenia':	3,
            'Madagascar':	3,
            'Tayikistán':	3,
            'Uganda':	3,
            'Comoras':	3,
            'Turkmenistán':	3,
            'Zimbabue':	3,
            'Camboya':	3,
            'Uzbekistán':	3,
            'República Democrática del Congo':	3,
            'Haití':	3,
            'Burundi':	3,
            'República Centroafricana':	3,
            'Chad':	3,
            'República del Congo':	3,
            'Angola':	3,
            'Eritrea':	3,
            'Venezuela':	3,
            'Irak':	3,
            'Guinea-Bissau':	3,
            'Afganistán':	3,
            'Libia':	3,
            'Yemen':	3,
            'Sudán':	3,
            'Siria':	3,
            'Corea del Norte':	3,
            'Sudán del Sur':	3,
            'Somalia':	3
        },
        jurisdiccion_estado: {
            'aguascalientes': 1,
            'baja california': 2,
            'baja california sur': 1,
            'campeche de zaragoza': 2,
            'chiapas ': 1,
            'chihuaha': 3,
            'colima': 1,
            'ciudad de mexico': 1,
            'durango': 2,
            'guanajuato': 1,
            'guerrero': 1,
            'hidalgo': 1,
            'jalisco': 1,
            'estado de mexico': 1,
            'michoacan de ocampo': 2,
            'morelos': 1,
            'nayarit': 1,
            'nuevo leon': 1,
            'oaxaca': 1,
            'puebla': 1,
            'queretaro': 1,
            'quintana roo': 1,
            'san luis potosi': 1,
            'sinaloa': 3,
            'sonora': 3,
            'tabasco': 1,
            'tamaulipas': 3,
            'tlaxcala': 1,
            'veracruz de ignacio de la llave': 1,
            'yucatan': 1,
            'zacatecas': 1,
            'default': 1
        },
        cliente_tipo_persona: {
            'fisica': 1,
            'moral': 2, 
            'default': 1
        },
        cliente_edad: {
            'edad_18-25': 3, 
            'edad_26-60': 1,
            'edad_60-75': 2
        },
        sign_alerta_historica: {
            'con': 3,
            'sin': 1,
            'default': 1
        },
        cambio_estatus: {
            'si': 3,
            'no': 1,
         },     
        pago_en_exceso: {
            'pago normal': 1,
            'menos o mas del 25': 2,
            'menos o mas del 50': 3
        },
        frecuencia: {
            'conforme al contrato': 1,
            '1 pago adicional': 2,
            '2 o mas pagos adicionales': 3
        },
        liquidacion_anticipada: {
            'ninguna': 1,
            'antes de la mitad del plazo': 2,
            'un 80 antes del plazo': 3
        },
        incremento_monto: {
            'si': 3,
            'no': 1
        }
    }
};

module.exports = riskMatrix;